server:
  port: ${random.int(8089,9090)}
  error:
    include-message: always
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false
  servlet:
    context-path: /bookings

spring:
  application:
    name: auto-hub-booking
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:p6spy:postgresql://localhost:5432/auto_hub_booking
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  cloud:
    loadbalancer:
      enabled: true
      cache:
        enabled: true
    consul:
      enabled: true
      host: localhost
      port: 8500
      discovery:
        enabled: true
        prefer-ip-address: true
        instanceId: ${spring.application.name}-id
        serviceName: ${spring.application.name}
        healthCheckPath: /actuator/health
        healthCheckInterval: 10s
        hostname: localhost
        failFast: false
    function:
      definition: bookingUpdateConsumer;failedCreatedBookingDlqConsumer;failedUpdatedBookingDlqConsumer;usernameConsumer
    stream:
      defaultBinder: kafka
      bindings:
        auditLogInfoProducer-out-0:
          destination: ${BOOKING_AUDIT_LOG_INFO_TOPIC}
          contentType: application/json
        deletedBookingProducer-out-0:
          destination: ${DELETED_BOOKING_TOPIC}
          contentType: application/json
        failedCreatedBookingDlqProducer-out-0:
          destination: ${FAILED_CREATED_BOOKING_DLQ_TOPIC}
          contentType: application/json
        failedUpdatedBookingDlqProducer-out-0:
          destination: ${FAILED_UPDATED_BOOKING_DLQ_TOPIC}
          contentType: application/json
        savedBookingProducer-out-0:
          destination: ${SAVED_BOOKING_TOPIC}
          contentType: application/json
        saveBookingCarUpdateProducer-out-0:
          destination: ${SAVE_BOOKING_CAR_UPDATE_TOPIC}
          contentType: application/json
        updateBookingCarsUpdateProducer-out-0:
          destination: ${UPDATE_BOOKING_CARS_UPDATE_TOPIC}
          contentType: application/json
        updatedBookingProducer-out-0:
          destination: ${UPDATED_BOOKING_TOPIC}
          contentType: application/json
        bookingUpdateConsumer-in-0:
          binder: kafka
          destination: ${BOOKING_UPDATE_TOPIC}
          contentType: application/json
          group: ${BOOKING_CONSUMER_GROUP}
          consumer:
            default-retryable: true
            max-attempts: 3
            back-off-max-interval: 10000
            back-off-multiplier: 1.0
        failedCreatedBookingDlqConsumer-in-0:
          binder: kafka
          destination: ${FAILED_CREATED_BOOKING_DLQ_TOPIC}
          contentType: application/json
          group: ${BOOKING_CONSUMER_GROUP}
          consumer:
            default-retryable: true
            max-attempts: 3
            back-off-max-interval: 10000
            back-off-multiplier: 1.0
        failedUpdatedBookingDlqConsumer-in-0:
          binder: kafka
          destination: ${FAILED_UPDATED_BOOKING_DLQ_TOPIC}
          contentType: application/json
          group: ${BOOKING_CONSUMER_GROUP}
          consumer:
            default-retryable: true
            max-attempts: 3
            back-off-max-interval: 10000
            back-off-multiplier: 1.0
        usernameConsumer-in-0:
          binder: kafka
          destination: ${USERNAME_TOPIC}
          contentType: application/json
          group: ${BOOKING_CONSUMER_GROUP}
          consumer:
            default-retryable: true
            max-attempts: 3
            back-off-max-interval: 10000
            back-off-multiplier: 1.0
      kafka:
        binder:
          auto-create-topics: true
          auto-add-partitions: false
          consumer-properties:
            key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            allow.auto.create.topics: true
            auto.offset.reset: latest
        bindings:
          bookingUpdateConsumer-in-0:
            consumer:
              ack-mode: MANUAL_IMMEDIATE
              standard-headers: both
          failedCreatedBookingDlqConsumer-in-0:
            consumer:
              ack-mode: MANUAL_IMMEDIATE
              standard-headers: both
          failedUpdatedBookingDlqConsumer-in-0:
            consumer:
              ack-mode: MANUAL_IMMEDIATE
              standard-headers: both
          usernameConsumer-in-0:
            consumer:
              ack-mode: MANUAL_IMMEDIATE
              standard-headers: both
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      enable-auto-commit: false
    producer:
      keySerializer: org.apache.kafka.common.serialization.StringSerializer
      valueSerializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
  data:
    redis:
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}
      port: 6379
      database: 0

management:
  server:
    port: ${server.port}
  endpoint:
    health:
      group:
        custom:
          show-components: always
          show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,loggers,prometheus
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

springdoc:
  swagger-ui:
    enabled: true
    path: /definition/swagger-ui.html
    operationsSorter: method
  api-docs:
    path: /definition/v3/api-docs

logging:
  level:
    org:
      springframework:
        security: ERROR
        web:
          csrf:
            CsrfFilter: ERROR
        jdbc:
          core:
            JdbcTemplate: ERROR
            StatementCreatorUtils: ERROR
      hibernate:
        SQL: ERROR
        type:
          descriptor:
            sql:
              BasicBinder: ERROR

apikey:
  secret: ${API_KEY_SECRET}

cors:
  mapping: '/**'
  allowedOrigins: '*'
  allowedMethods: '*'
  allowedHeaders: '*'

rest-client:
  url:
    auto-hub-agency-cars: http://auto-hub-agency/agency/cars

debezium:
  enabled: true
  connector-name: debezium-booking-postgres-connector
  server-name: booking-postgres-server
  server-id: 10182
  database-name: auto_hub_booking
  database-host: localhost
  database-port: 5432
  topic-name: ${DEBEZIUM_BOOKING_TOPIC}
  table-name: booking
  schema-name: public
  slot-name: booking_slot
  groupId: ${BOOKING_CONSUMER_GROUP}

audit:
  enabled: true

decorator:
  datasource:
    p6spy:
      enable-logging: true
      logging: slf4j
