services:
  postgres:
    image: 'postgres:16-alpine'
    environment:
      - 'POSTGRES_DB=swift_wheels_hub_agency'
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_PASSWORD=password'
    ports:
      - '5432:5432'
