server:
  port: ${PORT:0}
  error:
    include-message: always
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false

spring:
  application:
    name: car-rental-request-validator
  threads:
    virtual:
      enabled: true
  redis:
    host: ${REDIS_HOST}
    password: ${REDIS_PASSWORD}
    port: 6379
    database: 0

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_USER}:${EUREKA_PASSWORD}@localhost:8761/eureka
    registryFetchIntervalSeconds: 5
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10

management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus" ]

authentication:
  type: apikey

apikey-secret: ${API_KEY_SECRET}

swagger:
  agency: lb://car-rental-agency/agency/definition/v3/api-docs
  booking: lb://car-rental-booking/bookings/definition/v3/api-docs
  customer: lb://car-rental-customer/customers/definition/v3/api-docs
  expense: lb://car-rental-expense/expense/definition/v3/api-docs
