server:
  port: ${PORT:0}
  error:
    include-message: always
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false
  servlet:
    context-path: /bookings

spring:
  application:
    name: car-rental-booking
  thread-executor: virtual
  datasource:
    url: jdbc:postgresql://localhost:5432/car_rental_booking
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  mvc:
    throw-exception-if-no-handler-found: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_USER}:${EUREKA_PASSWORD}@localhost:8761/eureka
    registryFetchIntervalSeconds: 5
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10

management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus" ]

springdoc:
  swagger-ui:
    enabled: true
    path: /definition/swagger-ui.html
    operationsSorter: method
  api-docs:
    path: /definition/v3/api-docs

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web:
          csrf:
            CsrfFilter: DEBUG
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

authentication:
  type: apikey
  secret: ${API_KEY_SECRET}

cross-origin: '*'

rest-template:
  enabled: true
  hostname: lb://car-rental-booking
  url:
    car-rental-agency-branches: lb://car-rental-agency/agency/branches
    car-rental-agency-cars: lb://car-rental-agency/agency/cars
    car-rental-agency-employees: lb://car-rental-agency/agency/employees
    car-rental-customer: lb://car-rental-customer/customers
    car-rental-expense: lb://car-rental-expense/expense/invoices
  config:
    pool-size: 5
    idle-connection-wait-time: 30000
    socket-timeout: 60000
    request-timeout: 30000
    connect-timeout: 30000
    default-keep-alive-time: 20000
    max-localhost-connections: 80
    max-total-connections: 40
    max-route-connections: 40

kafka:
  enabled: true
  producer: true
  booking-producer: true
  saved-booking-producer-topic-name: ${SAVED_BOOKING_TOPIC}
  updated-booking-producer-topic-name: ${UPDATED_BOOKING_TOPIC}
  deleted-booking-producer-topic-name: ${DELETED_BOOKING_TOPIC}
  deleted-user-topic-name: ${DELETED_USER_TOPIC}
  audit-log-topic-name: ${BOOKING_AUDIT_LOG_INFO_TOPIC}
  groupId: ${BOOKING_CONSUMER_GROUP}

debezium:
  enabled: true
  connector-name: debezium-booking-postgres-connector
  server-name: booking-postgres-server
  server-id: 10182
  database-name: car_rental_booking
  database-host: localhost
  database-port: 5432
  topic-name: ${DEBEZIUM_BOOKING_TOPIC}
  table-name: booking
  schema-name: public
  slot-name: booking_slot
  groupId: ${BOOKING_CONSUMER_GROUP}

audit:
  enabled: true
