-- liquibase formatted sql

-- changeset George Niculae:1
CREATE TABLE IF NOT EXISTS public.invoice_document
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    invoice_id        BIGINT       NOT NULL,
    customer_username VARCHAR(255) NOT NULL,
    customer_email    VARCHAR(255) NOT NULL,
    created_at        TIMESTAMP    NOT NULL,
    content           BYTEA        NOT NULL,
    CONSTRAINT pk_invoice_document PRIMARY KEY (id)
);

-- changeset George Niculae:2
CREATE UNIQUE INDEX IF NOT EXISTS idx_invoice_document_invoice_id
    ON public.invoice_document (invoice_id);
