server:
  port: 0
  servlet:
    context-path: /ai

spring:
  application:
    name: auto-hub-ai
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/auto_hub_ai
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: mistral
          temperature: 0.0F
      embedding:
        options:
          model: nomic-embed-text
    vectorstore:
      pgvector:
        initialize-schema: false
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 768
  cloud:
    loadbalancer:
      enabled: true
      cache:
        enabled: true
    function:
      definition: carAvailableConsumer;carStatusUpdateConsumer;updateCarsConsumer;carUpdateDetailsConsumer
    stream:
      defaultBinder: kafka
      bindings:
        carAvailableConsumer-in-0:
          binder: kafka
          destination: ${CAR_AVAILABLE_AI_TOPIC}
          contentType: application/json
          group: ${AI_CONSUMER_GROUP}
          consumer:
            default-retryable: true
            max-attempts: 3
            back-off-max-interval: 10000
            back-off-multiplier: 1.0
        carStatusUpdateConsumer-in-0:
          binder: kafka
          destination: ${SAVE_BOOKING_CAR_UPDATE_TOPIC}
          contentType: application/json
          group: ${AI_CONSUMER_GROUP}
          consumer:
            default-retryable: true
            max-attempts: 3
            back-off-max-interval: 10000
            back-off-multiplier: 1.0
        updateCarsConsumer-in-0:
          binder: kafka
          destination: ${UPDATE_BOOKING_CARS_UPDATE_TOPIC}
          contentType: application/json
          group: ${AI_CONSUMER_GROUP}
          consumer:
            default-retryable: true
            max-attempts: 3
            back-off-max-interval: 10000
            back-off-multiplier: 1.0
        carUpdateDetailsConsumer-in-0:
          binder: kafka
          destination: ${INVOICE_CAR_UPDATE_DETAILS_TOPIC}
          contentType: application/json
          group: ${AI_CONSUMER_GROUP}
          consumer:
            default-retryable: true
            max-attempts: 3
            back-off-max-interval: 10000
            back-off-multiplier: 1.0
      kafka:
        binder:
          auto-create-topics: true
          auto-add-partitions: false
          consumer-properties:
            key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            allow.auto.create.topics: true
            auto.offset.reset: latest
        bindings:
          carAvailableConsumer-in-0:
            consumer:
              ack-mode: MANUAL_IMMEDIATE
          carStatusUpdateConsumer-in-0:
            consumer:
              ack-mode: MANUAL_IMMEDIATE
          updateCarsConsumer-in-0:
            consumer:
              ack-mode: MANUAL_IMMEDIATE
          carUpdateDetailsConsumer-in-0:
            consumer:
              ack-mode: MANUAL_IMMEDIATE
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      enable-auto-commit: false
    listener:
      missing-topics-fatal: false
  web:
    error:
      include-message: always
      include-binding-errors: never
      include-stacktrace: never
      include-exception: false

eureka:
  client:
    enabled: true
    healthcheck:
      enabled: true
    eureka-server-port: 8761
    service-url:
      defaultZone: http://localhost:8761/eureka/
    proxy-password: ${EUREKA_USER}
    proxy-user-name: ${EUREKA_PASSWORD}
  instance:
    prefer-ip-address: true

springdoc:
  swagger-ui:
    enabled: true
    path: /definition/swagger-ui.html
    operationsSorter: method
  api-docs:
    path: /definition/v3/api-docs

management:
  server:
    port: ${server.port}
  endpoint:
    health:
      group:
        custom:
          show-components: always
          show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,loggers,prometheus
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

logging:
  level:
    org:
      springframework:
        security: ERROR
        web:
          csrf:
            CsrfFilter: ERROR

apikey:
  secret: ${API_KEY_SECRET}
  system-roles: ROLE_admin,ROLE_user

cors:
  mapping: '/**'
  allowedOrigins: '*'
  allowedMethods: '*'
  allowedHeaders: '*'

rest-client:
  url:
    auto-hub-agency-cars: http://auto-hub-agency/agency/cars
