server:
  port: ${PORT:0}
  error:
    include-message: always
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false

spring:
  application:
    name: swift-wheels-hub-audit
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/swift_wheels_hub_audit
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  cloud:
    discovery:
      enabled: true
    function:
      definition: bookingAuditInfoConsumer;customerAuditInfoConsumer;expenseAuditInfoConsumer
    stream:
      bindings:
        bookingAuditInfoConsumer-in-0:
          binder: kafka
          destination: ${BOOKING_AUDIT_LOG_INFO_TOPIC}
          contentType: application/json
          group: ${AUDIT_CONSUMER_GROUP}
        customerAuditInfoConsumer-in-0:
          binder: kafka
          destination: ${CUSTOMER_AUDIT_LOG_INFO_TOPIC}
          contentType: application/json
          group: ${AUDIT_CONSUMER_GROUP}
        expenseAuditInfoConsumer-in-0:
          binder: kafka
          destination: ${EXPENSE_AUDIT_LOG_INFO_TOPIC}
          contentType: application/json
          group: ${AUDIT_CONSUMER_GROUP}
      kafka:
        binder:
          auto-create-topics: true
          auto-add-partitions: false
          consumer-properties:
            key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            allow.auto.create.topics: true
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      missing-topics-fatal: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_USER}:${EUREKA_PASSWORD}@localhost:8761/eureka
    registryFetchIntervalSeconds: 5
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10

management:
  server:
    port: ${PORT:0}
  endpoint:
    loggers:
      enabled: true
    health:
      group:
        custom:
          show-components: always
          show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,loggers,prometheus
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web:
          csrf:
            CsrfFilter: DEBUG
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

kafka:
  enabled: true
  booking-audit-log-info-topic-name: ${BOOKING_AUDIT_LOG_INFO_TOPIC}
  customer-audit-log-info-topic-name: ${CUSTOMER_AUDIT_LOG_INFO_TOPIC}
  expense-audit-log-info-topic-name: ${EXPENSE_AUDIT_LOG_INFO_TOPIC}
  groupId: ${AUDIT_CONSUMER_GROUP}
