server:
  port: ${PORT:8088}
  error:
    include-message: always
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false

spring:
  application:
    name: swift-wheels-hub-api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/swift-wheels-hub
          jwk-set-uri: http://localhost:8080/realms/swift-wheels-hub/protocol/openid-connect/certs
  codec:
    max-in-memory-size: 20MB
  cloud:
    loadbalancer:
      enabled: true
      ribbon:
        enabled: false
      cache:
        enabled: false
    consul:
      enabled: true
      config:
        enabled: false
        acl-token: ${CONSUL_ACL_TOKEN}
      host: localhost
      port: 8500
      discovery:
        enabled: true
        prefer-ip-address: true
        instanceId: ${spring.application.name}-id
        serviceName: ${spring.application.name}
        healthCheckPath: /actuator/health
        healthCheckInterval: 10s
        hostname: localhost
        failFast: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: agency
          uri: lb://swift-wheels-hub-agency
          predicates:
            - Path=/agency/**
          filters:
            - name: ServiceIdHeader
              args:
                serviceId: "swift-wheels-hub-agency"
        - id: ai
          uri: lb://swift-wheels-hub-ai
          predicates:
            - Path=/ai/**
          filters:
            - name: ServiceIdHeader
              args:
                serviceId: "swift-wheels-hub-ai"
        - id: booking
          uri: lb://swift-wheels-hub-booking
          predicates:
            - Path=/bookings/**
          filters:
            - name: ServiceIdHeader
              args:
                serviceId: "swift-wheels-hub-booking"
        - id: customer
          uri: lb://swift-wheels-hub-customer
          predicates:
            - Path=/customers/**
          filters:
            - name: ServiceIdHeader
              args:
                serviceId: "swift-wheels-hub-customer"
        - id: expense
          uri: lb://swift-wheels-hub-expense
          predicates:
            - Path=/expense/**
          filters:
            - name: ServiceIdHeader
              args:
                serviceId: "swift-wheels-hub-expense"

management:
  server:
    port: ${PORT:8088}
  endpoint:
    loggers:
      enabled: true
    health:
      group:
        custom:
          show-components: always
          show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,loggers,prometheus
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

logging:
  level:
    org:
      springframework:
        security: ERROR
        web:
          csrf:
            CsrfFilter: ERROR

apikey-secret: ${API_KEY_SECRET}

request-validator-url: http://swift-wheels-hub-request-validator/validate
