-- liquibase formatted sql

-- changeset George Niculae:1
CREATE TABLE IF NOT EXISTS public.branch
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255),
    region       VARCHAR(255),
    address      VARCHAR(255),
    phone_number VARCHAR(255),
    CONSTRAINT pk_branch PRIMARY KEY (id)
);

-- changeset George Niculae:2
-- preconditions onFail:MARK_RAN
-- precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM branch
INSERT INTO public.branch (name, region, address, phone_number)
VALUES ('Ploiesti Branch', 'Ploiesti', 'Ploiesti', '0722222222');

INSERT INTO public.branch (name, region, address, phone_number)
VALUES ('Bucuresti Branch', 'Bucuresti', 'Bucuresti', '0733333333');
