-- liquibase formatted sql

-- changeset George Niculae:1
CREATE TABLE IF NOT EXISTS public.rental_office
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(255),
    city      VARCHAR(255),
    address   VARCHAR(255),
    branch_id BIGINT NOT NULL,
    CONSTRAINT pk_rental_office PRIMARY KEY (id)
);

ALTER TABLE public.rental_office
    ADD CONSTRAINT FK_RENTAL_OFFICE_ON_BRANCH
        FOREIGN KEY (branch_id)
            REFERENCES public.branch (id);

-- changeset George Niculae:2
-- preconditions onFail:MARK_RAN
-- precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM rental_office
INSERT INTO public.rental_office (name, city, address, branch_id)
VALUES ('Ploiesti Rental Office', 'Ploiesti', 'Ploiesti', 1);

INSERT INTO public.rental_office (name, city, address, branch_id)
VALUES ('Bucuresti Rental Office', 'Bucuresti', 'Bucuresti', 2);
