server:
  port: ${random.int(8089,9090)}
  error:
    include-message: always
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false

spring:
  application:
    name: auto-hub-audit
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:p6spy:postgresql://localhost:5432/auto_hub_audit
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  cloud:
    loadbalancer:
      enabled: true
      cache:
        enabled: true
    consul:
      enabled: true
      host: localhost
      port: 8500
      discovery:
        enabled: true
        prefer-ip-address: true
        instanceId: ${spring.application.name}-id
        serviceName: ${spring.application.name}
        healthCheckPath: /actuator/health
        healthCheckInterval: 10s
        hostname: localhost
        failFast: false
    function:
      definition: auditInfoConsumer
    stream:
      defaultBinder: kafka
      bindings:
        auditInfoConsumer-in-0:
          binder: kafka
          destination: ${AUDIT_LOG_INFO_TOPIC}
          contentType: application/json
          group: ${AUDIT_CONSUMER_GROUP}
          consumer:
            default-retryable: true
            max-attempts: 3
            back-off-max-interval: 10000
            back-off-multiplier: 1.0
      kafka:
        binder:
          auto-create-topics: true
          auto-add-partitions: false
          consumer-properties:
            key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            allow.auto.create.topics: true
        bindings:
          auditInfoConsumer-in-0:
            consumer:
              ack-mode: MANUAL_IMMEDIATE
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      missing-topics-fatal: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

management:
  server:
    port: ${server.port}
  endpoint:
    health:
      group:
        custom:
          show-components: always
          show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,loggers,prometheus
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

logging:
  level:
    org:
      springframework:
        security: ERROR
        web:
          csrf:
            CsrfFilter: ERROR
        jdbc:
          core:
            JdbcTemplate: ERROR
            StatementCreatorUtils: ERROR
      hibernate:
        SQL: ERROR
        type:
          descriptor:
            sql:
              BasicBinder: ERROR

decorator:
  datasource:
    p6spy:
      enable-logging: true
      logging: slf4j
