server:
  port: ${PORT:0}
  error:
    include-message: always
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false
  servlet:
    context-path: /expense

spring:
  application:
    name: swift-wheels-hub-expense
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/swift_wheels_hub_expense
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  mvc:
    throw-exception-if-no-handler-found: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      missing-topics-fatal: false
  sendgrid:
    api-key: ${SENDGRID_API_KEY}

authentication:
  type: apikey
  secret: ${API_KEY_SECRET}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_USER}:${EUREKA_PASSWORD}@localhost:8761/eureka
    registryFetchIntervalSeconds: 5
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10

springdoc:
  swagger-ui:
    enabled: true
    path: /definition/swagger-ui.html
    operationsSorter: method
  api-docs:
    path: /definition/v3/api-docs

management:
  server:
    port: ${PORT:0}
  endpoint:
    loggers:
      enabled: true
    health:
      group:
        custom:
          show-components: always
          show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,loggers,prometheus
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web:
          csrf:
            CsrfFilter: DEBUG
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

debezium:
  enabled: true
  connector-name: debezium-expense-postgres-connector
  server-name: expense-postgres-server
  server-id: 10183
  database-name: swift_wheels_hub_expense
  database-host: localhost
  database-port: 5432
  topic-name: ${DEBEZIUM_EMAIL_NOTIFICATION_TOPIC}
  table-name: invoice
  schema-name: public
  slot-name: invoice_slot
  groupId: ${EXPENSE_CONSUMER_GROUP}

rest-client:
  url:
    swift-wheels-hub-bookings: lb://swift-wheels-hub-booking/bookings
    swift-wheels-hub-agency-branches: lb://swift-wheels-hub-agency/agency/branches
    swift-wheels-hub-agency-cars: lb://car-rental-agency/agency/cars
    swift-wheels-hub-agency-employees: lb://swift-wheels-hub-agency/agency/employees

kafka:
  enabled: true
  producer: true
  saved-booking-producer-topic-name: ${SAVED_BOOKING_TOPIC}
  updated-booking-producer-topic-name: ${UPDATED_BOOKING_TOPIC}
  deleted-booking-producer-topic-name: ${DELETED_BOOKING_TOPIC}
  email-notification-producer-topic-name: ${EMAIL_NOTIFICATION_TOPIC}
  audit-log-topic-name: ${EXPENSE_AUDIT_LOG_INFO_TOPIC}
  groupId: ${EXPENSE_CONSUMER_GROUP}

sendgrid:
  enabled: true
  mail:
    mailFrom: ${SENDGRID_MAIL_FROM}
    name: Car Rental

mustache-template:
  enabled: true
