server:
  port: ${PORT:0}
  error:
    include-message: always
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false
  servlet:
    context-path: /agency

spring:
  application:
    name: car-rental-agency
  thread-executor: virtual
  datasource:
    url: jdbc:postgresql://localhost:5432/car_rental_agency
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  mvc:
    throw-exception-if-no-handler-found: true
  kafka:
    bootstrap-servers: localhost:9092
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  cloud:
    discovery:
      enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 15MB
      max-request-size: 15MB

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_USER}:${EUREKA_PASSWORD}@localhost:8761/eureka
    registryFetchIntervalSeconds: 5
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10

springdoc:
  swagger-ui:
    enabled: true
    path: /definition/swagger-ui.html
    operationsSorter: method
  api-docs:
    path: /definition/v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus" ]

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web:
          csrf:
            CsrfFilter: DEBUG
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

authentication:
  type: apikey
  secret: ${API_KEY_SECRET}

cross-origin: '*'
