server:
  port: ${random.int(8089,9090)}
  error:
    include-message: always
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false
  servlet:
    context-path: /agency

spring:
  application:
    name: swift-wheels-hub-agency
  threads:
    virtual:
      enabled: true
  codec:
    max-in-memory-size: 20MB
  datasource:
    url: jdbc:p6spy:postgresql://localhost:5432/swift_wheels_hub_agency
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  cloud:
    loadbalancer:
      enabled: true
      ribbon:
        enabled: false
      cache:
        enabled: true
    consul:
      enabled: true
      config:
        enabled: false
        acl-token: ${CONSUL_ACL_TOKEN}
      host: localhost
      port: 8500
      discovery:
        enabled: true
        prefer-ip-address: true
        instanceId: ${spring.application.name}-id
        serviceName: ${spring.application.name}
        healthCheckPath: /actuator/health
        healthCheckInterval: 10s
        hostname: localhost
        failFast: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 15MB
      max-request-size: 15MB
  sql:
    init:
      mode: always
  docker:
    compose:
      enabled: false

springdoc:
  swagger-ui:
    enabled: true
    path: /definition/swagger-ui.html
    operationsSorter: method
  api-docs:
    path: /definition/v3/api-docs

management:
  server:
    port: ${server.port}
  endpoint:
    loggers:
      enabled: true
    health:
      group:
        custom:
          show-components: always
          show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,loggers,prometheus
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

logging:
  level:
    org:
      springframework:
        security: ERROR
        web:
          csrf:
            CsrfFilter: ERROR
        jdbc:
          core:
            JdbcTemplate: ERROR
            StatementCreatorUtils: ERROR
      hibernate:
        SQL: ERROR
        type:
          descriptor:
            sql:
              BasicBinder: ERROR

apikey:
  secret: ${API_KEY_SECRET}

decorator:
  datasource:
    p6spy:
      enable-logging: true
      logging: slf4j
