server:
  port: ${PORT:8085}
  error:
    include-message: always
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false
  servlet:
    context-path: /expense

spring:
  application:
    name: car-rental-expense
  thread-executor: virtual
  datasource:
    url: jdbc:postgresql://localhost:5432/car_rental_expense
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  mvc:
    throw-exception-if-no-handler-found: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      missing-topics-fatal: false
  sendgrid:
    api-key: ${SENDGRID_API_KEY}

authentication:
  type: apikey
  secret: ${API_KEY_SECRET}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_USER}:${EUREKA_PASSWORD}@localhost:8761/eureka
    registryFetchIntervalSeconds: 5
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10

springdoc:
  swagger-ui:
    enabled: true
    path: /definition/swagger-ui.html
    operationsSorter: method
  api-docs:
    path: /definition/v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus" ]

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web:
          csrf:
            CsrfFilter: DEBUG
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

cross-origin: '*'

debezium:
  enabled: true
  connector-name: debezium-expense-postgres-connector
  server-name: expense-postgres-server
  server-id: 10183
  database-name: car_rental_expense
  database-host: localhost
  database-port: 5432
  topic-name: ${DEBEZIUM_EMAIL_NOTIFICATION_SERVICE_TOPIC}
  table-name: invoice
  schema-name: public
  slot-name: invoice_slot
  groupId: ${EXPENSE_CONSUMER_GROUP}

rest-template:
  enabled: true
  hostname: lb://car-rental-expense
  url:
    car-rental-bookings: lb://car-rental-booking/bookings
    car-rental-agency-branches: lb://car-rental-agency/agency/branches
    car-rental-agency-cars: lb://car-rental-agency/agency/cars
    car-rental-agency-employees: lb://car-rental-agency/agency/employees
  config:
    pool-size: 5
    idle-connection-wait-time: 30000
    socket-timeout: 60000
    request-timeout: 30000
    connect-timeout: 30000
    default-keep-alive-time: 20000
    max-localhost-connections: 80
    max-total-connections: 40
    max-route-connections: 40

kafka:
  enabled: true
  producer: true
  saved-booking-producer-topic-name: ${SAVED_BOOKING_PRODUCER_TOPIC}
  updated-booking-producer-topic-name: ${UPDATED_BOOKING_PRODUCER_TOPIC}
  deleted-booking-producer-topic-name: ${DELETED_BOOKING_PRODUCER_TOPIC}
  email-notification-producer-topic-name: ${EMAIL_NOTIFICATION_PRODUCER_TOPIC}
  audit-log-topic-name: ${EXPENSE_AUDIT_LOG_INFO_PRODUCER_TOPIC}
  groupId: ${EXPENSE_CONSUMER_GROUP}

sendgrid:
  enabled: true
  mail:
    mailFrom: ${SENDGRID_MAIL_FROM}
    name: Car Rental

mustache-template:
  enabled: true
