server:
  port: ${PORT:0}
  error:
    include-message: always
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false

spring:
  application:
    name: car-rental-audit
    thread-executor: virtual
  datasource:
    url: jdbc:postgresql://localhost:5432/car_rental_audit
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  mvc:
    throw-exception-if-no-handler-found: true
  kafka:
    bootstrap-servers: localhost:9092
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_USER}:${EUREKA_PASSWORD}@localhost:8761/eureka
    registryFetchIntervalSeconds: 5
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10

management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus" ]

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web:
          csrf:
            CsrfFilter: DEBUG
        jdbc:
          core:
            JdbcTemplate: DEBUG
            StatementCreatorUtils: TRACE
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

kafka:
  enabled: true
  booking-audit-log-info-topic-name: ${BOOKING_AUDIT_LOG_INFO_TOPIC}
  customer-audit-log-info-topic-name: ${CUSTOMER_AUDIT_LOG_INFO_TOPIC}
  expense-audit-log-info-topic-name: ${EXPENSE_AUDIT_LOG_INFO_TOPIC}
  groupId: ${AUDIT_CONSUMER_GROUP}
